🌍 Add .DS_Store to .gitignore
loolabs/clubs pull request #10
Opened 2021-01-23 21:10 UTC by jeffzh4ng

2021-01-23 21:12 UTC, xujustinj requested changes

2021-01-23 21:12 UTC, xujustinj commented on .gitignore
> +.DS_Store
```suggestion
.DS_Store

```

2021-01-23 21:15 UTC, jeffzh4ng commented on .gitignore
> +.DS_Store
Done

2021-01-28 01:01 UTC, jeffzh4ng commented
Closed by #11

2021-01-28 01:01 UTC, closed without merging